# Generated by Django 4.1.5 on 2023-01-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_story_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="date_now",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="date_time_now",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
