# Generated by Django 4.1.5 on 2023-01-16 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_department_role"),
    ]

    operations = [
        migrations.RemoveField(model_name="userinfo", name="age",),
    ]
