# Generated by Django 4.1.5 on 2023-01-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_userinfo_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="age",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
