# Generated by Django 4.1.5 on 2023-01-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_userinfo_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="data",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
