# Generated by Django 4.1.5 on 2023-01-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_userinfo_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
                ("content", models.TextField()),
                ("time", models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name="userinfo", name="age", field=models.IntegerField(default=1),
        ),
    ]
