# Generated by Django 4.1.5 on 2023-01-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_delete_works"),
    ]

    operations = [
        migrations.CreateModel(
            name="Works",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
                ("src", models.CharField(max_length=255)),
                ("href", models.CharField(max_length=255)),
                ("time", models.DateField()),
            ],
        ),
    ]
