# Generated by Django 4.1.5 on 2023-01-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_works"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=255)),
            ],
        ),
    ]
