# Generated by Django 4.1.5 on 2023-01-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="ip",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
